using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Cenmetrix.Cemex.Message
{
  public static  class BaseTemplate
    {

      public static string Get()
      {
            StringBuilder template = new StringBuilder();

            template.Append("<html>");
            template.Append("<head>");
            template.Append("</head>");
            template.Append("<body>");
            template.Append("    <style type=\"text/css\">");
            template.Append("        <!-- .rps_6204 #x_outlook a {");
            template.Append("            padding: 0;");
            template.Append("        }");
            template.Append("        .rps_6204 .x_ReadMsgBody {");
            template.Append("            width: 100%;");
            template.Append("        }");
            template.Append("        .rps_6204 .x_ExternalClass {");
            template.Append("            width: 100%;");
            template.Append("        }");
            template.Append("        .rps_6204 .x_ExternalClass, .rps_6204 .x_ExternalClass p, .rps_6204 .x_ExternalClass span, .rps_6204 .x_ExternalClass font, .rps_6204 .x_ExternalClass td, .rps_6204 .x_ExternalClass div {");
            template.Append("            line-height: 100%;");
            template.Append("        }");
            template.Append("        .rps_6204 body {");
            template.Append("            margin: 0;");
            template.Append("            padding: 0;");
            template.Append("            height: 100% !important;");
            template.Append("            width: 100% !important;");
            template.Append("        }");
            template.Append("        .rps_6204 table {");
            template.Append("            border-collapse: collapse !important;");
            template.Append("            font-weight: normal;");
            template.Append("        }");
            template.Append("        .rps_6204 tr {");
            template.Append("            font-size: 0px;");
            template.Append("        }");
            template.Append("        .rps_6204 td {");
            template.Append("            border-collapse: collapse !important;");
            template.Append("            margin: 0;");
            template.Append("            padding: 0;");
            template.Append("        }");
            template.Append("        .rps_6204 .x_ExternalClass .x_ecxhm {");
            template.Append("            display: none !important;");
            template.Append("        }");
            template.Append("        .rps_6204 .x_ExternalClass .x_ecxhm2 {");
            template.Append("            display: inline !important;");
            template.Append("        }");
            template.Append("        .rps_6204 .x_appleBody a {");
            template.Append("            color: #68440a;");
            template.Append("            text-decoration: none;");
            template.Append("        }");
            template.Append("        .rps_6204 .x_appleFooter a {");
            template.Append("            color: #999999;");
            template.Append("            text-decoration: none;");
            template.Append("        }");
            template.Append("        .rps_6204 a img {");
            template.Append("            border: none;");
            template.Append("        }");
            template.Append("        .rps_6204 ax_[x-apple-data-detectors] {");
            template.Append("            color: inherit !important;");
            template.Append("            text-decoration: none !important;");
            template.Append("            font-size: inherit !important;");
            template.Append("            font-family: inherit !important;");
            template.Append("            font-weight: inherit !important;");
            template.Append("            line-height: inherit !important;");
            template.Append("        }");
            template.Append("        .rps_6204 div, .rps_6204 span, .rps_6204 p {");
            template.Append("            margin: 0;");
            template.Append("            padding: 0;");
            template.Append("        }");
            template.Append("        .rps_6204 img {");
            template.Append("            border: 0;");
            template.Append("            height: auto;");
            template.Append("            line-height: 100%;");
            template.Append("            outline: none;");
            template.Append("            text-decoration: none;");
            template.Append("        }");
            template.Append("        .rps_6204 sup, .rps_6204 sub {");
            template.Append("            vertical-align: baseline;");
            template.Append("            top: -0.4em;");
            template.Append("        }");
            template.Append("        .rps_6204 sub {");
            template.Append("            top: 0.4em;");
            template.Append("        }");
            template.Append("        -->");
            template.Append("    </style>");
            template.Append("    <div>");
            template.Append("        <div>");
            template.Append("            <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\" class=\"x_container\">");
            template.Append("                <tbody>");
            template.Append("<tr>");
            template.Append("                        <td align=\"center\" style=\"font-size:1px; line-height:1px\">");
            template.Append("                            <div style=\"display:none; width:0px; max-height:0px; overflow:hidden\">#sub-title#");
            template.Append("</div>");
            template.Append("                        </td>");
            template.Append("                    </tr>");
            template.Append("                    <tr>");
            template.Append("                        <td align=\"center\" bgcolor=\"#ffffff\">");
            template.Append("                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" align=\"center\" style=\"margin:0 auto;\">");
            template.Append("                                <tbody>");
            template.Append("                                    <tr>");
            template.Append("                                        <td>");
            template.Append("                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">");
            template.Append("                                                <tbody>");
            template.Append("                                                    <tr>");
            template.Append("                                                        <td align=\"right\" bgcolor=\"#ffffff\" class=\"x_mobile-no-side-padding\" style=\"background-color: #ffffff;\">");
            template.Append("                                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">");
            template.Append("                                                                <tbody>");
            template.Append("                                                                    <tr></tr>");
            template.Append("                                                                    <tr>");
            template.Append("                                                                        <td align=\"right\" class=\"x_mobile-side-padding-10\" style=\"padding-bottom: 5px;padding-top: 5px;padding-right: 0px;\">   <img src=\"#imageUrl#\" alt=\"Cemex\" width=\"170\" height=\"60\" border=\"0\" style=\"display:block;outline:none;border:none;width: 170px;\"></td>");
            template.Append("                                                                    </tr>");
            template.Append("                                                                </tbody>");
            template.Append("                                                            </table>");
            template.Append("                                                        </td>");
            template.Append("                                                    </tr>");
            template.Append("                                                </tbody>");
            template.Append("                                            </table>");
            template.Append("                                        </td>");
            template.Append("                                    </tr>");
            template.Append("                                    <tr>");
            template.Append("                                        <td>");
            template.Append("                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">");
            template.Append("                                                <tbody>");
            template.Append("                                                    <tr>");
            template.Append("                                                        <td align=\"center\" bgcolor=\"#eef1f5\" class=\"x_mobile-no-side-padding\" style=\"padding: 15px;background-color: #eef1f5;\">");
            template.Append("                                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">");
            template.Append("                                                                <tbody>");
            template.Append("                                                                    <tr>");
            template.Append("                                                                        <td class=\"x_mobile-headline x_mobile-side-padding-10\" align=\"center\" bgcolor=\"#2b5797\" style=\"font-family:'Segoe UI Light',SUWL,'Segoe UI',Verdana,sans-serif;font-size: 18px;line-height:25px;color: #ffffff;padding-left:17px;padding-right:17px;padding-bottom: 5px;padding-top: 20px;font-weight: bold;background-color: #2b5797;padding-bottom: 20px;\">");
            template.Append("                                                                            #title#");
            template.Append("                                                                        </td>");
            template.Append("                                                                    </tr>");
            template.Append("                                                                    <tr>");
            template.Append("                                                                        <td align=\"center\" bgcolor=\"#ffffff\" class=\"x_mobile-side-padding-10\" style=\"font-family:'Segoe UI','Segoe UI Regular',SUWR,Verdana,sans-serif;font-size:14px;line-height:21px;color: #656768;padding-left:17px;padding-right:17px;padding-bottom:20px;padding-top: 20px;font-weight: 600;\">");
            template.Append("                                                                           #sub-title#");
            template.Append("                                                                        </td>");
            template.Append("                                                                    </tr>");
            template.Append("                                                                    #table# #table-rows# #button#");
            template.Append("                                                                    <tr>");
            template.Append("                                                                        <td align=\"center\" class=\"x_mobile-side-padding-10\" style=\"font-family:'Segoe UI','Segoe UI Regular',SUWR,Verdana,sans-serif;font-size:11px;line-height:15px;color:#727272;padding-bottom: 1px;padding-top: 10px;text-align: center;\">");
            template.Append("                                                                            Copyright © " + DateTime.Now.Year +" Cemex Software (Pvt) Ltd.");
            template.Append("                                                                            All rights reserved");
            template.Append("                                                                        </td>");
            template.Append("                                                                    </tr>");
            template.Append("                                                                    <tr>");
            template.Append("                                                                        <td align=\"center\" class=\"x_mobile-side-padding-10\" style=\"font-family:'Segoe UI','Segoe UI Regular',SUWR,Verdana,sans-serif;font-size:11px;line-height:15px;color:#727272;padding-bottom:10px;padding-top: 10px;text-align: center;vertical-align: super;\">");
            template.Append("                                                                            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"width:100%; border-collapse:collapse;\">");
            template.Append("                                                                                <tbody>");
            template.Append("                                                                                    <tr>");
            template.Append("                                                                                        <td style=\"text-align: center;font-family: 'Segoe UI','Segoe UI Regular',SUWR,Verdana,sans-serif;font-size: 12px;line-height:15px;color:#727272;padding-bottom: 3px;padding-top: 1px;text-align: center;\">");
            template.Append("                                                                                            Powered by");
            template.Append("                                                                                        </td>");
            template.Append("                                                                                    </tr>");
            template.Append("                                                                                    <tr>");
            template.Append("                                                                                        <td style=\"text-align: center;\">");
            template.Append("                                                                                            <img src=\"https://www.cemex.cloud/Images/CemexMailerLogo.png\" alt=\"Cemex\" width=\"62\" height=\"18\" border=\"0\" style=\"outline:none;border:none;width: 62px;\">");
            template.Append("                                                                                        </td>");
            template.Append("                                                                                    </tr>");
            template.Append("                                                                                </tbody>");
            template.Append("                                                                            </table>");
            template.Append("                                                                        </td>");
            template.Append("                                                                    </tr>");
            template.Append("                                                                </tbody>");
            template.Append("                                                            </table>");
            template.Append("                                                        </td>");
            template.Append("                                                    </tr>");
            template.Append("                                                </tbody>");
            template.Append("                                            </table>");
            template.Append("                                        </td>");
            template.Append("                                    </tr>");
            template.Append("                                </tbody>");
            template.Append("                            </table>");
            template.Append("                        </td>");
            template.Append("                    </tr>");
            template.Append("                </tbody>");
            template.Append("            </table>");
            template.Append("        </div>");
            template.Append("    </div>");
            template.Append("</body>");
            template.Append("</html>");

            return template.ToString();

      }
  }
}
